# Generated by Django 4.0.5 on 2022-07-05 04:24

import StudyApps.Stack.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fromCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='csv/')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='https://yt3.ggpht.com/a/AATXAJz4KIO1eJuU6U6hW4ZO_r4eRkQLnNOUtMQ2Dw=s900-c-k-c0xffffffff-no-rj-mo')),
                ('title', models.CharField(max_length=50, unique=True, validators=[StudyApps.Stack.validators.validate_title])),
                ('text', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('topics', models.ManyToManyField(blank=True, to='Stack.topic')),
            ],
        ),
    ]
