# Generated by Django 4.0.5 on 2022-07-12 14:18

import Stack.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='https://yt3.ggpht.com/a/AATXAJz4KIO1eJuU6U6hW4ZO_r4eRkQLnNOUtMQ2Dw=s900-c-k-c0xffffffff-no-rj-mo')),
                ('title', models.CharField(max_length=50, unique=True, validators=[Stack.validators.validate_title])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('events', models.ManyToManyField(blank=True, related_name='stack_events', to='Stack.event')),
            ],
        ),
    ]
